# Generated by Django 3.2.7 on 2021-10-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(decimal_places=6, max_digits=32)),
                ('february', models.DecimalField(decimal_places=6, max_digits=32)),
                ('march', models.DecimalField(decimal_places=6, max_digits=32)),
                ('april', models.DecimalField(decimal_places=6, max_digits=32)),
                ('may', models.DecimalField(decimal_places=6, max_digits=32)),
                ('june', models.DecimalField(decimal_places=6, max_digits=32)),
                ('july', models.DecimalField(decimal_places=6, max_digits=32)),
                ('august', models.DecimalField(decimal_places=6, max_digits=32)),
                ('september', models.DecimalField(decimal_places=6, max_digits=32)),
                ('october', models.DecimalField(decimal_places=6, max_digits=32)),
                ('november', models.DecimalField(decimal_places=6, max_digits=32)),
                ('december', models.DecimalField(decimal_places=6, max_digits=32)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('manager', models.CharField(max_length=32)),
                ('budget', models.DecimalField(decimal_places=6, max_digits=32)),
                ('monthly_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.monthlybudget')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=32)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactiontype')),
            ],
        ),
    ]
