# Generated by Django 3.2.7 on 2021-11-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='april',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='august',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='december',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='february',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='january',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='july',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='june',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='march',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='may',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='november',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='october',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='september',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
    ]
